apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: juice-shop-pod-kill
  namespace: juice-shop
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - juice-shop
    labelSelectors:
      app: juice-shop
