apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-analyzer
  namespace: k8sgpt-operator-system

spec:
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.32

  ai:
    enabled: true
    backend: azureopenai
    baseUrl: https://for-k8s-resource.services.ai.azure.com/
    engine: gpt-4.1-mini
    model: gpt-4.1-mini
    secret:
      name: k8sgpt-api-secret
      key: openai-api-key